install vim bash cmatrix cowsay git python
install hr hub toilet tree wget youtube-dl
install trash  node --without-npm
link --force git python

cask install alfred atom cheatsheet dash dropbox filezilla flux google-chrome hive minecraft
cask install onyx popcorn-time silverlight spotify steam torbrowser transmission unrarx vlc
